steps of making pandas

In [6]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\cordial space\appdata\roaming\python\python314\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\cordial space\appdata\roaming\python\python314\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cordial space\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\cordial space\appdata\roaming\python\python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\cordial space\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd;

using data frame for my data

In [8]:
data = {
    "Name": ["John", "Alice", "Bob","Mike"],
    "Age": [20, 25, 22, 30]
}

dataFrame = pd.DataFrame(data)

printing my data frame

In [9]:
print(dataFrame)

    Name  Age
0   John   20
1  Alice   25
2    Bob   22
3   Mike   30

sttructure of my data

In [10]:
dataFrame.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

description of my data

In [11]:
dataFrame.describe()

             Age
count   4.000000
mean   24.250000
std     4.349329
min    20.000000
25%    21.500000
50%    23.500000
75%    26.250000
max    30.000000

Entering csv fille

In [12]:
peopleCsv=pd.read_csv("people.csv")

In [13]:
people=pd.DataFrame(peopleCsv)

In [14]:
print(people)

    Index          User Id First Name  Last Name     Sex  \
0       1  88F7B33d2bcf9f5     Shelby    Terrell    Male
1       2  f90cD3E76f1A9b9    Phillip    Summers  Female
2       3  DbeAb8CcdfeFC2c   Kristine     Travis    Male
3       4  A31Bee3c201ef58    Yesenia   Martinez    Male
4       5  1bA7A3dc874da3c       Lori       Todd    Male
..    ...              ...        ...        ...     ...
95     96  5eFda7caAeB260E     Dennis     Barnes  Female
96     97  CCbFce93d3720bE      Steve  Patterson  Female
97     98  2fEc528aFAF0b69     Wesley       Bray    Male
98     99  Adc7ad9B6e4A1Fe     Summer   Oconnell  Female
99    100  b8D0aD3490FC7e1     Mariah    Bernard    Male

                         Email                   Phone Date of birth  \
0         elijah57@example.net  001-084-906-7849x73518    1945-10-26
1        bethany14@example.com       214.112.6044x4913    1910-03-24
2        bthompson@example.com            277.609.7938    1992-07-02
3    kaitlinkaiser@example.com            584.094.6111    2017-08-03
4   buchananmanuel@example.net       689-207-3558x7233    1938-12-01
..                         ...                     ...           ...
95         bmartin@example.org    001-095-524-2112x257    1954-07-30
96       latasha46@example.net        001-865-478-5157    1932-04-29
97        regina11@example.org      995-542-3004x76800    1994-12-28
98  alexiscantrell@example.org    001-273-685-6932x092    2012-04-12
99       pcopeland@example.org     (341)594-6554x44657    2016-11-15

                Job Title
0         Games developer
1          Phytotherapist
2               Homeopath
3       Market researcher
4      Veterinary surgeon
..                    ...
95      Software engineer
96              Barrister
97         Police officer
98   Broadcast journalist
99  IT sales professional

[100 rows x 9 columns]

In [15]:
people.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [16]:
people.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          100 non-null    int64
 1   User Id        100 non-null    str
 2   First Name     100 non-null    str
 3   Last Name      100 non-null    str
 4   Sex            100 non-null    str
 5   Email          100 non-null    str
 6   Phone          100 non-null    str
 7   Date of birth  100 non-null    str
 8   Job Title      100 non-null    str
dtypes: int64(1), str(8)
memory usage: 7.2 KB

In [18]:
people['Email']

0           elijah57@example.net
1          bethany14@example.com
2          bthompson@example.com
3      kaitlinkaiser@example.com
4     buchananmanuel@example.net
                 ...
95           bmartin@example.org
96         latasha46@example.net
97          regina11@example.org
98    alexiscantrell@example.org
99         pcopeland@example.org
Name: Email, Length: 100, dtype: str